In [1]:
import numpy as np

## №2

In [2]:
def order(a):
    '''Сортирует массив индексов от нуля до m исходя из a[i]
    >>> a.shape
    (n,)
    '''
    m = a.shape[0] #длина списка
    b, c = np.arange(m), a.copy() #список индексов, массив
    #сортировка пузырьком
    for i in range(m - 1):
        for j in range(m - 1):
            if c[j] >= c[j + 1]:
                c[j], c[j + 1] = c[j + 1], c[j]
                b[j], b[j + 1] = b[j + 1], b[j]
    return b

In [3]:
a = np.random.randint(10, size=(5, 6))
print(a, a[:, order(a[0])], sep='\n\n')

[[9 8 6 8 0 1]
 [2 7 3 5 4 5]
 [4 2 6 5 5 7]
 [0 2 5 9 4 4]
 [5 7 8 8 7 8]]

[[0 1 6 8 8 9]
 [4 5 3 7 5 2]
 [5 7 6 2 5 4]
 [4 4 5 2 9 0]
 [7 8 8 7 8 5]]


## №3

In [4]:
def smoothing(a):
    n, m = a.shape #размерность матрицы
    b = np.zeros(a.shape) #матрица из нулей для заполнения
    for i in range(n):
        for j in range(m):
            p = a[(i + 1) % n, j] #сосед справа
            q = a[(i - 1) % n, j] #сосед слева
            r = a[i, (j + 1) % m] #сосед снизу
            s = a[i, (j - 1) % m] #сосед справа
            b[i, j] = (p + q + r + s) / 4 #среднее арифметическое соседей
    return b

In [5]:
a = np.random.randint(10, size=(5, 6))
print(a, smoothing(a), sep='\n\n')

[[6 3 3 5 4 2]
 [8 4 0 4 0 7]
 [4 2 8 6 8 1]
 [8 3 9 3 9 7]
 [5 0 8 3 3 6]]

[[4.5  3.25 4.   3.5  2.5  5.75]
 [5.25 3.25 4.75 2.75 5.75 2.75]
 [4.75 4.75 4.25 5.75 4.   6.5 ]
 [4.75 4.75 5.5  6.75 5.25 6.  ]
 [5.   4.75 3.75 4.75 5.5  4.25]]


## №4

In [6]:
def secondary_mirroring(a):
    n, m = a.shape #размерность
    b = np.zeros((m, n), dtype='int64') #заготовка из нулей
    for i in range(n):
        for j in range(m):
            b[m - j - 1, n - i - 1] = a[i, j] #побочнодиагональное отзеркаливание
    return b

In [7]:
a = np.random.randint(10, size=(5, 6))
print(a, secondary_mirroring(a), sep='\n\n')

[[3 2 0 6 1 8]
 [8 2 2 1 0 0]
 [7 3 3 0 0 8]
 [1 7 6 2 1 6]
 [0 5 1 6 2 1]]

[[1 6 8 0 8]
 [2 1 0 0 1]
 [6 2 0 1 6]
 [1 6 3 2 0]
 [5 7 3 2 2]
 [0 1 7 8 3]]


## №5

In [8]:
def zmeyuka(m, n):
    b = np.arange(1, 1 + m*n).reshape((m, n)) #нарезаем arange
    for i in range(m):
        if i % 2:
            b[i] = b[i, ::-1] #разворачиваем каждую вторую строку
    return b

In [9]:
n = 18
print(zmeyuka(n, n))

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18]
 [ 36  35  34  33  32  31  30  29  28  27  26  25  24  23  22  21  20  19]
 [ 37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54]
 [ 72  71  70  69  68  67  66  65  64  63  62  61  60  59  58  57  56  55]
 [ 73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90]
 [108 107 106 105 104 103 102 101 100  99  98  97  96  95  94  93  92  91]
 [109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126]
 [144 143 142 141 140 139 138 137 136 135 134 133 132 131 130 129 128 127]
 [145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162]
 [180 179 178 177 176 175 174 173 172 171 170 169 168 167 166 165 164 163]
 [181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198]
 [216 215 214 213 212 211 210 209 208 207 206 205 204 203 202 201 200 199]
 [217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234]
 [252 251 250 249 248 247